testing: True
data:
  eth_price_file: '/home/pjp18/Documents/marble_2020/data/marble-data/data/eth-prices.json'
  gas_price_file: '/home/pjp18/Documents/marble_2020/data/marble-data/data/gas-prices-with-timestamp-partial.jsonl.gz'
  features:
    - 'average_gas_price'
    - 'contracts_tx_count'
  nested_features:
    - max_price_tx: 'gas_price'
    - min_price_tx: 'gas_price'
  eth_price_features:
    - 'open_price'
    - 'date'
  start_date: '2020-01-14'
  end_date: '2020-01-15'
model:
  hidden_size: 64
  input_size: 4
  num_layers: 3
  pred_steps: 16
  dropout: 0.1
  linear_units: 512