testing: False
# Denote the type of model you want: simple or distribution
type: 'simple'
data:
#  eth_price_file: '/home/pjp18/Documents/marble_data/eth-prices.json'
  eth_price_file: '/home/pjp18/Documents/marble_data/eth-prices-ticks.csv'
  gas_price_file: '/home/pjp18/Documents/marble_data/gas-prices-with-txs-3months.jsonl.gz'
  data_path: '/home/pjp18/Documents/marble_data/prep.pickle'
  features:
    - 'average_gas_price'
    - 'tx_count'
  nested_features:
    - max_price_tx: 'gas_price'
    - min_price_tx: 'gas_price'
  inc_transactions: False
  eth_price_features:
    - 'value'
    - 'date'
  lagged_cols:
    - average_gas_price
  start_date: '2019-11-10'
  end_date: '2019-11-25'
#  start_date: '2020-01-10'
#  end_date: '2020-01-12'
  window_size: 288
  y_len: 12
  sample_freq: 2
  train_prop: 0.7
  batch_size: 32
  y_cols:
    - 'min_price_tx'
#    - 'average_gas_price'
#    - 'std_dev'
  scaling:
    normalizer: minmax
    columns:
      - average_gas_price
      - average_gas_price_lagged
      - max_price_tx
      - min_price_tx
      - tx_count
      - value
      - mean
      - std_dev
  remove_outliers:
    - average_gas_price
    - max_price_tx
    - min_price_tx
    - mean
    - std_dev
    - value
  # Set to False to disable resampling
  resample: 5T
  fft: True
  energy: 0.8
model:
  hidden_size: 128
  input_size: 6
  num_layers: 2
  # pred_steps must match y_len
  pred_steps: 12
  dropout: 0.01
  linear_units: 512
training:
  optimizer:
    # pass in class available in torch.optim
    class: Adam
    args: {}
  num_epochs: 20
  learning_rate: 0.0015
  log_path: '/home/pjp18/Documents/marble_logs/'
  show_plots: True
  save_model: True

