testing: False
# Denote the type of model you want: simple or distribution
type: 'distribution'
data:
  eth_price_file: '/home/pjp18/Documents/marble_data/eth-prices.json'
  gas_price_file: '/home/pjp18/Documents/marble_data/gas-prices-with-txs-3months.jsonl.gz'
  # feature order is maintained, date is dropped
  features:
    - 'average_gas_price'
    - 'tx_count'
  nested_features:
    - max_price_tx: 'gas_price'
    - min_price_tx: 'gas_price'
  inc_transactions: False
  eth_price_features:
    - 'open_price'
    - 'date'
  start_date: '2020-01-09'
  end_date: '2020-01-16'
  window_size: 50
  y_len: 10
  sample_freq: 10
  train_prop: 0.7
  batch_size: 32
  y_cols:
    - 'average_gas_price'
  scaling:
    - average_gas_price: 'log'
    - max_price_tx: 'log'
    - min_price_tx: 'log'
  dist_scaling: 'log'
model:
  hidden_size: 64
  input_size: 5
  num_layers: 2
  # pred_steps must match y_len
  pred_steps: 10
  dropout: 0.1
  linear_units: 512
training:
  optimizer:
    # pass in class available in torch.optim
    class: RMSprop
    args: {}
  num_epochs: 20
  learning_rate: 0.005
  log_path: '/home/pjp18/Documents/marble_logs/'
  show_plots: True
  save_model: False

